#version: '3'
#services:
#  monapp:
#    image: zainebkhlifi1/monapp:latest
#    ports:
#      - "8086:8086"
#    restart: always

version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  monapp:
    image: zainebkhlifi1/monapp:latest
    container_name: monapp
    depends_on:
      - mysql
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql-data: